// Generated by scripts/prepare_extra_samples.py from the pinned sample mappings.
export const INSTRUMENTS = [
  {
    "id": "salamander",
    "name": "Salamander grand",
    "family": "keys",
    "range": [
      36,
      84
    ],
    "license": "CC BY 3.0",
    "drone": false
  },
  {
    "id": "wurlitzer",
    "name": "Wurlitzer EP200",
    "family": "keys",
    "range": [
      36,
      84
    ],
    "license": "CC BY 3.0",
    "drone": true
  },
  {
    "id": "guitar-electric",
    "name": "guitar · clean electric",
    "family": "guitars",
    "range": [
      36,
      84
    ],
    "license": "CC0 1.0",
    "drone": false
  },
  {
    "id": "guitar-acoustic",
    "name": "guitar · acoustic",
    "family": "guitars",
    "range": [
      36,
      84
    ],
    "license": "CC0 1.0",
    "drone": false
  },
  {
    "id": "vibraphone",
    "name": "vibraphone · soft mallets",
    "family": "mallets",
    "range": [
      53,
      84
    ],
    "license": "CC0 1.0",
    "drone": false
  },
  {
    "id": "vibraphone-hard",
    "name": "vibraphone · hard mallets",
    "family": "mallets",
    "range": [
      53,
      84
    ],
    "license": "CC0 1.0",
    "drone": false
  },
  {
    "id": "bowed-vibraphone",
    "name": "bowed vibraphone",
    "family": "mallets",
    "range": [
      57,
      84
    ],
    "license": "CC0 1.0",
    "drone": false
  },
  {
    "id": "marimba",
    "name": "marimba",
    "family": "mallets",
    "range": [
      41,
      84
    ],
    "license": "CC0 1.0",
    "drone": false
  },
  {
    "id": "renaissance-organ",
    "name": "Renaissance organ · 8′",
    "family": "organs",
    "range": [
      36,
      84
    ],
    "license": "CC0 1.0",
    "drone": true
  },
  {
    "id": "renaissance-organ-full",
    "name": "Renaissance organ · full",
    "family": "organs",
    "range": [
      36,
      84
    ],
    "license": "CC0 1.0",
    "drone": true
  },
  {
    "id": "pipe-organ",
    "name": "pipe organ · quiet",
    "family": "organs",
    "range": [
      36,
      84
    ],
    "license": "CC0 1.0",
    "drone": true
  },
  {
    "id": "pipe-organ-full",
    "name": "pipe organ · full",
    "family": "organs",
    "range": [
      36,
      84
    ],
    "license": "CC0 1.0",
    "drone": true
  },
  {
    "id": "tx81z",
    "name": "TX81Z · FM piano",
    "family": "synths",
    "range": [
      36,
      84
    ],
    "license": "CC0 1.0",
    "drone": false
  },
  {
    "id": "tx81z-clavi",
    "name": "TX81Z · clavisynth",
    "family": "synths",
    "range": [
      36,
      84
    ],
    "license": "CC0 1.0",
    "drone": false
  },
  {
    "id": "tx81z-piano",
    "name": "TX81Z · piano",
    "family": "synths",
    "range": [
      36,
      84
    ],
    "license": "CC0 1.0",
    "drone": false
  },
  {
    "id": "concert-harp",
    "name": "concert harp",
    "family": "plucked strings",
    "range": [
      36,
      84
    ],
    "license": "CC0 1.0",
    "drone": false
  },
  {
    "id": "kalimba",
    "name": "kalimba · Kenya",
    "family": "plucked strings",
    "range": [
      59,
      84
    ],
    "license": "CC0 1.0",
    "drone": false
  },
  {
    "id": "kalimba-tanzania",
    "name": "kalimba · Tanzania",
    "family": "plucked strings",
    "range": [
      43,
      84
    ],
    "license": "CC0 1.0",
    "drone": false
  },
  {
    "id": "rhodes",
    "name": "Rhodes Mark I",
    "family": "keys",
    "range": [
      36,
      84
    ],
    "license": "CC BY-NC 4.0",
    "drone": false
  }
];
export const instrumentById = id => INSTRUMENTS.find(instrument => instrument.id === id) || INSTRUMENTS[0];
